version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
    command: ["poetry", "run", "python", "run.py"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run alembic upgrade head
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres

volumes:
  pgdata:
