version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${POSTGRES_DATABASE_URL}
    command: ["poetry", "run", "python", "run.py"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run alembic upgrade head
    depends_on:
      - db
    environment:
      DATABASE_URL: ${POSTGRES_DATABASE_URL}

volumes:
  pgdata:
