"""Изменение таблиц Project, Task

Revision ID: 4118c20b4448
Revises: 9cebb003a9e1
Create Date: 2024-06-21 21:26:05.674861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4118c20b4448'
down_revision: Union[str, None] = '9cebb003a9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'start_time',
                    existing_type=sa.DateTime(),
                    existing_nullable=False,
                    nullable=True
                    )
    op.alter_column('projects', 'end_time',
                    existing_type=sa.DateTime(),
                    existing_nullable=False,
                    nullable=True
                    )
    op.alter_column('tasks', 'start_time',
                    existing_type=sa.DateTime(),
                    existing_nullable=False,
                    nullable=True
                    )
    op.alter_column('tasks', 'end_time',
                    existing_type=sa.DateTime(),
                    existing_nullable=False,
                    nullable=True
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'start_time',
                    existing_type=sa.DateTime(),
                    existing_nullable=True,
                    nullable=False
                    )
    op.alter_column('projects', 'end_time',
                    existing_type=sa.DateTime(),
                    existing_nullable=True,
                    nullable=False
                    )
    op.alter_column('tasks', 'start_time',
                    existing_type=sa.DateTime(),
                    existing_nullable=True,
                    nullable=False
                    )
    op.alter_column('tasks', 'end_time',
                    existing_type=sa.DateTime(),
                    existing_nullable=True,
                    nullable=False
                    )
    # ### end Alembic commands ###
