"""Second migration

Revision ID: 8e77a3d255fe
Revises: 60aef39934cd
Create Date: 2024-05-26 21:38:32.276937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e77a3d255fe'
down_revision: Union[str, None] = '60aef39934cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('tasks_table')
    op.drop_table('task_executors')
    op.add_column('projects', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.execute('UPDATE projects SET start_time = NOW() WHERE start_time IS NULL')
    op.alter_column('projects', 'start_time', nullable=False)
    op.add_column('projects', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.execute('UPDATE projects SET end_time = NOW() WHERE end_time IS NULL')
    op.alter_column('projects', 'end_time', nullable=False)
    op.drop_column('projects', 'created_at')
    op.add_column('tasks', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('executor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'executors', ['executor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'executor_id')
    op.drop_column('tasks', 'end_time')
    op.drop_column('tasks', 'start_time')
    op.add_column('projects', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'end_time')
    op.drop_column('projects', 'start_time')
    op.create_table('task_executors',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('executor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], name='task_executors_executor_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_executors_task_id_fkey'),
    sa.PrimaryKeyConstraint('task_id', 'executor_id', name='task_executors_pkey')
    )
    op.create_table('tasks_table',
    sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('executor', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('task_id', name='tasks_table_pkey')
    )
    # ### end Alembic commands ###
