"""Увеличение длины поля password до 256 символов

Revision ID: 9ceae42b48f4
Revises: ad668636318a
Create Date: 2024-05-28 21:56:52.507135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ceae42b48f4'
down_revision: Union[str, None] = 'ad668636318a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('executors', 'password',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('executors', 'password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
