version: 1
disable_existing_loggers: False
formatters:
  request_formatter:
    (): config.custom_logger.RequestFormatter
    format: '[%(asctime)s] %(remote_addr)s %(username)s requested %(url)s %(levelname)s in %(module)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: request_formatter
    stream: ext://sys.stdout
  rotating_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: request_formatter
    filename: app.log
    when: D
    interval: 1
    backupCount: 7


